# fly.toml app configuration file generated for muba-3rjv-a on 2025-04-21T04:19:36Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'muba-3rjv-a'
primary_region = 'nrt'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
